import { type ClassValue, clsx } from 'clsx'
import { extendTailwindMerge } from 'tailwind-merge'

const SEMANTIC_COLORS = [
  'canvas',
  'surface',
  'surface-raised',
  'surface-sunken',
  'surface-hover',
  'surface-active',
  'overlay',
  'fg',
  'fg-muted',
  'fg-subtle',
  'fg-inverted',
  'line',
  'line-subtle',
  'line-strong',
  'brand',
  'brand-hover',
  'brand-active',
  'brand-subtle',
  'brand-muted',
  'brand-fg',
  'accent',
  'accent-hover',
  'accent-subtle',
  'accent-fg',
  'success',
  'success-subtle',
  'success-fg',
  'warning',
  'warning-subtle',
  'warning-fg',
  'danger',
  'danger-hover',
  'danger-subtle',
  'danger-fg',
  'info',
  'info-subtle',
  'info-fg',
  'ring',
] as const

const FONT_SIZES = ['2xs', 'xs', 'sm', 'base', 'md', 'lg', 'xl', '2xl', '3xl', '4xl', '5xl'] as const

const SPACING = [
  'field',
  'stack',
  'gutter',
  'section',
  'page',
  'control-xs',
  'control-sm',
  'control-md',
  'control-lg',
  'control-xl',
  'brandbar',
  'sidebar',
  'sidebar-collapsed',
  'row',
  'row-dense',
  'prose',
  'content',
  'content-wide',
] as const

const twMerge = extendTailwindMerge({
  extend: {
    classGroups: {
      'font-size': [{ text: [...FONT_SIZES] }],
      'text-color': [{ text: [...SEMANTIC_COLORS] }],
      'bg-color': [{ bg: [...SEMANTIC_COLORS] }],
      'border-color': [{ border: [...SEMANTIC_COLORS] }],
      'ring-color': [{ ring: [...SEMANTIC_COLORS] }],
      'outline-color': [{ outline: [...SEMANTIC_COLORS] }],
      'divide-color': [{ divide: [...SEMANTIC_COLORS] }],
      'shadow-color': [{ shadow: [...SEMANTIC_COLORS] }],
      p: [{ p: [...SPACING] }],
      px: [{ px: [...SPACING] }],
      py: [{ py: [...SPACING] }],
      pt: [{ pt: [...SPACING] }],
      pr: [{ pr: [...SPACING] }],
      pb: [{ pb: [...SPACING] }],
      pl: [{ pl: [...SPACING] }],
      m: [{ m: [...SPACING] }],
      mx: [{ mx: [...SPACING] }],
      my: [{ my: [...SPACING] }],
      mt: [{ mt: [...SPACING] }],
      mr: [{ mr: [...SPACING] }],
      mb: [{ mb: [...SPACING] }],
      ml: [{ ml: [...SPACING] }],
      gap: [{ gap: [...SPACING] }],
      'gap-x': [{ 'gap-x': [...SPACING] }],
      'gap-y': [{ 'gap-y': [...SPACING] }],
      w: [{ w: [...SPACING] }],
      h: [{ h: [...SPACING] }],
      'min-w': [{ 'min-w': [...SPACING] }],
      'min-h': [{ 'min-h': [...SPACING] }],
      'max-w': [{ 'max-w': [...SPACING] }],
      'max-h': [{ 'max-h': [...SPACING] }],
      'space-x': [{ 'space-x': [...SPACING] }],
      'space-y': [{ 'space-y': [...SPACING] }],
      inset: [{ inset: [...SPACING] }],
      top: [{ top: [...SPACING] }],
      right: [{ right: [...SPACING] }],
      bottom: [{ bottom: [...SPACING] }],
      left: [{ left: [...SPACING] }],
      'line-clamp': [{ clamp: ['1', '2', '3', '4', '5', '6', 'none'] }],
    },
  },
})

export function cn(...inputs: ClassValue[]): string {
  return twMerge(clsx(inputs))
}
